#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : freetype
Version  : 2.10.4
Release  : 503
URL      : file:///aot/build/clearlinux/packages/freetype/freetype-v2-10-4.tar.gz
Source0  : file:///aot/build/clearlinux/packages/freetype/freetype-v2-10-4.tar.gz
Source1  : file:///aot/build/clearlinux/packages/freetype/freetype-demos-v2-10-4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : FTL GPL-2.0+ MIT Zlib
BuildRequires : GoogleBenchmark-dev
BuildRequires : ImageMagick-dev
BuildRequires : LuaJIT-dev
BuildRequires : LuaJIT-staticdev
BuildRequires : SDL2
BuildRequires : SDL2-dev
BuildRequires : SDL2-staticdev
BuildRequires : Sphinx
BuildRequires : Vulkan-Headers-dev
BuildRequires : Vulkan-Loader-dev
BuildRequires : acl
BuildRequires : acl-dev
BuildRequires : acl-staticdev
BuildRequires : alsa-lib-dev
BuildRequires : alsa-lib-lib
BuildRequires : alsa-tools
BuildRequires : asciidoctor-dev
BuildRequires : binutils
BuildRequires : binutils-dev
BuildRequires : binutils-staticdev
BuildRequires : brotli
BuildRequires : brotli-dev
BuildRequires : brotli-dev32
BuildRequires : brotli-staticdev
BuildRequires : brotli-staticdev32
BuildRequires : buildreq-cmake
BuildRequires : buildreq-meson
BuildRequires : buildreq-qmake
BuildRequires : bzip2
BuildRequires : bzip2-dev
BuildRequires : bzip2-dev32
BuildRequires : bzip2-staticdev
BuildRequires : ca-certs
BuildRequires : ca-certs-static
BuildRequires : cairo
BuildRequires : cairo-dev
BuildRequires : cairo-lib
BuildRequires : ccache
BuildRequires : clazy
BuildRequires : cmake
BuildRequires : cmake-dev
BuildRequires : cppcheck
BuildRequires : curl-dev
BuildRequires : curl-staticdev
BuildRequires : dav1d-dev
BuildRequires : dav1d-staticdev
BuildRequires : dbus
BuildRequires : dbus-broker
BuildRequires : dbus-dev
BuildRequires : dbus-glib
BuildRequires : dbus-glib-dev
BuildRequires : dbus-python
BuildRequires : doxygen
BuildRequires : e2fsprogs-dev
BuildRequires : elfutils-dev
BuildRequires : elfutils-staticdev
BuildRequires : evtest
BuildRequires : expat-dev
BuildRequires : expat-dev32
BuildRequires : expat-staticdev
BuildRequires : fakechroot-dev
BuildRequires : fakechroot-staticdev
BuildRequires : fftw-dev
BuildRequires : fftw-staticdev
BuildRequires : findutils
BuildRequires : flac-dev
BuildRequires : flac-staticdev
BuildRequires : fontconfig-data
BuildRequires : fontconfig-dev
BuildRequires : fontconfig-lib
BuildRequires : fontconfig-staticdev
BuildRequires : freetype-dev
BuildRequires : freetype-lib
BuildRequires : freetype-staticdev
BuildRequires : fribidi-dev
BuildRequires : fribidi-staticdev
BuildRequires : gcc
BuildRequires : gcc-abi
BuildRequires : gcc-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-doc
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libs-math
BuildRequires : gcc-libstdc++32
BuildRequires : gcc-libubsan
BuildRequires : gcc-locale
BuildRequires : gdb
BuildRequires : gdb-dev
BuildRequires : gettext
BuildRequires : glib
BuildRequires : glib-bin
BuildRequires : glib-data
BuildRequires : glib-dev
BuildRequires : glib-lib
BuildRequires : glib-staticdev
BuildRequires : glibc
BuildRequires : glibc-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-lib-avx2
BuildRequires : glibc-libc32
BuildRequires : glibc-staticdev
BuildRequires : gmp
BuildRequires : gmp-dev
BuildRequires : gmp-staticdev
BuildRequires : gnutls
BuildRequires : gnutls-dev
BuildRequires : googletest
BuildRequires : googletest-dev
BuildRequires : graphite
BuildRequires : graphite-dev
BuildRequires : graphite-staticdev
BuildRequires : gsm-dev
BuildRequires : gsm-staticdev
BuildRequires : gtk+-data
BuildRequires : gtk+-lib
BuildRequires : gtk3-lib
BuildRequires : harfbuzz-dev
BuildRequires : harfbuzz-dev32
BuildRequires : harfbuzz-lib
BuildRequires : harfbuzz-staticdev
BuildRequires : harfbuzz-staticdev32
BuildRequires : icu4c-lib
BuildRequires : insync-dev
BuildRequires : json-c-dev
BuildRequires : json-c-staticdev
BuildRequires : jsoncpp
BuildRequires : jsoncpp-dev
BuildRequires : jsoncpp-lib
BuildRequires : jsoncpp-staticdev
BuildRequires : kakadu-dev
BuildRequires : keyutils
BuildRequires : keyutils-dev
BuildRequires : krb5
BuildRequires : krb5-dev
BuildRequires : l-smash-dev
BuildRequires : l-smash-staticdev
BuildRequires : ladspa_sdk-dev
BuildRequires : ladspa_sdk-staticdev
BuildRequires : lcms2-dev
BuildRequires : lcms2-staticdev
BuildRequires : libX11-data
BuildRequires : libX11-dev
BuildRequires : libX11-lib
BuildRequires : libXScrnSaver
BuildRequires : libXScrnSaver-dev
BuildRequires : libXScrnSaver-lib
BuildRequires : libXau-dev
BuildRequires : libXau-lib
BuildRequires : libXcursor-dev
BuildRequires : libXcursor-lib
BuildRequires : libXdamage-dev
BuildRequires : libXdamage-lib
BuildRequires : libXdmcp-dev
BuildRequires : libXdmcp-lib
BuildRequires : libXext-dev
BuildRequires : libXext-lib
BuildRequires : libXfont2-dev
BuildRequires : libXft-dev
BuildRequires : libXft-lib
BuildRequires : libXi-dev
BuildRequires : libXi-lib
BuildRequires : libXrender-dev
BuildRequires : libXrender-lib
BuildRequires : libXtst-dev
BuildRequires : libXtst-lib
BuildRequires : libXxf86vm-dev
BuildRequires : libXxf86vm-lib
BuildRequires : libaom-dev
BuildRequires : libaom-staticdev
BuildRequires : libarchive
BuildRequires : libarchive-dev
BuildRequires : libarchive-staticdev
BuildRequires : libcap
BuildRequires : libcap-dev
BuildRequires : libcap-ng-dev
BuildRequires : libconfig-dev
BuildRequires : libconfig-staticdev
BuildRequires : libdrm
BuildRequires : libdrm-dev
BuildRequires : libdrm-lib
BuildRequires : libdrm-staticdev
BuildRequires : libedit
BuildRequires : libedit-dev
BuildRequires : libffi
BuildRequires : libffi-dev
BuildRequires : libffi-staticdev
BuildRequires : libgcc1
BuildRequires : libgcrypt
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error
BuildRequires : libgpg-error-dev
BuildRequires : libidn2
BuildRequires : libidn2-dev
BuildRequires : libidn2-staticdev
BuildRequires : libinput-data
BuildRequires : libinput-dev
BuildRequires : libinput-lib
BuildRequires : libinput-libexec
BuildRequires : libjpeg-turbo-dev
BuildRequires : libjpeg-turbo-staticdev
BuildRequires : libpciaccess-dev
BuildRequires : libpng-dev
BuildRequires : libpng-dev32
BuildRequires : libpng-lib
BuildRequires : libpng-staticdev
BuildRequires : libsamplerate-dev
BuildRequires : libsamplerate-staticdev
BuildRequires : libsndfile-dev
BuildRequires : libsndfile-staticdev
BuildRequires : libsrt-dev
BuildRequires : libsrt-staticdev
BuildRequires : libstdc++
BuildRequires : libstdc++-dev
BuildRequires : libtasn1-dev
BuildRequires : libtasn1-staticdev
BuildRequires : libtheora-dev
BuildRequires : libtheora-staticdev
BuildRequires : libudfread-dev
BuildRequires : libudfread-staticdev
BuildRequires : libunistring-dev
BuildRequires : libunistring-staticdev
BuildRequires : libusb
BuildRequires : libusb-dev
BuildRequires : libva
BuildRequires : libva-dev
BuildRequires : libva-lib
BuildRequires : libvdpau
BuildRequires : libvdpau-dev
BuildRequires : libxcb-dev
BuildRequires : libxcb-lib
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : libxslt-bin
BuildRequires : libxslt-dev
BuildRequires : libxslt-staticdev
BuildRequires : libxvid-dev
BuildRequires : libxvid-staticdev
BuildRequires : libzimg-dev
BuildRequires : libzimg-staticdev
BuildRequires : lrzip-dev
BuildRequires : lrzip-staticdev
BuildRequires : lz4
BuildRequires : lz4-dev
BuildRequires : lz4-staticdev
BuildRequires : lzo
BuildRequires : lzo-dev
BuildRequires : lzo-staticdev
BuildRequires : md4c
BuildRequires : md4c-dev
BuildRequires : md4c-staticdev
BuildRequires : mediasdk-dev
BuildRequires : mesa
BuildRequires : mesa-dev
BuildRequires : mesa-lib
BuildRequires : mm-common-dev
BuildRequires : nasm
BuildRequires : nasm-bin
BuildRequires : ncurses-dev
BuildRequires : ninja
BuildRequires : numlockx
BuildRequires : nv-codec-headers-dev
BuildRequires : opencl-headers
BuildRequires : opencl-headers-dev
BuildRequires : openjpeg-dev
BuildRequires : openjpeg-staticdev
BuildRequires : openssl
BuildRequires : openssl-dev
BuildRequires : openssl-lib
BuildRequires : openssl-staticdev
BuildRequires : opus-dev
BuildRequires : opus-staticdev
BuildRequires : orc-dev
BuildRequires : orc-staticdev
BuildRequires : p11-kit
BuildRequires : p11-kit-dev
BuildRequires : pacrunner
BuildRequires : pacrunner-dev
BuildRequires : pango-lib
BuildRequires : pax-utils
BuildRequires : pcre-dev
BuildRequires : pcre-staticdev
BuildRequires : pcre2-dev
BuildRequires : pcre2-staticdev
BuildRequires : perl
BuildRequires : perl(XML::Parser)
BuildRequires : perl-Config-General
BuildRequires : perl-Config-Tiny
BuildRequires : perl-Crypt-SSLeay
BuildRequires : perl-DBI
BuildRequires : perl-DateTime-TimeZone
BuildRequires : perl-Encode-Locale
BuildRequires : perl-Error
BuildRequires : perl-File-Listing
BuildRequires : perl-HTML-Parser
BuildRequires : perl-HTML-Tagset
BuildRequires : perl-HTTP-Cookies
BuildRequires : perl-HTTP-Date
BuildRequires : perl-HTTP-Message
BuildRequires : perl-HTTP-Negotiate
BuildRequires : perl-IO-HTML
BuildRequires : perl-LWP-MediaTypes
BuildRequires : perl-LWP-Protocol-https
BuildRequires : perl-Params-Validate
BuildRequires : perl-Test-Simple
BuildRequires : perl-Try-Tiny
BuildRequires : perl-URI
BuildRequires : perl-XML-NamespaceSupport
BuildRequires : perl-XML-Parser
BuildRequires : perl-libwww-perl
BuildRequires : perl-man
BuildRequires : pixman
BuildRequires : pixman-dev
BuildRequires : pixman-lib
BuildRequires : pixman-staticdev
BuildRequires : pkg-config
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(harfbuzz)
BuildRequires : pkgconfig(libbrotlicommon)
BuildRequires : pkgconfig(libbrotlidec)
BuildRequires : pkgconfig(libbrotlienc)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(zlib)
BuildRequires : pulseaudio
BuildRequires : pulseaudio-dev
BuildRequires : pyelftools
BuildRequires : python3-core
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : qca-qt5
BuildRequires : qca-qt5-dev
BuildRequires : qt3d
BuildRequires : qt3d-dev
BuildRequires : qt5ct
BuildRequires : qtbase
BuildRequires : qtbase-dev
BuildRequires : qtbase-extras
BuildRequires : qtcanvas3d
BuildRequires : qtcharts
BuildRequires : qtcharts-dev
BuildRequires : qtconnectivity
BuildRequires : qtconnectivity-dev
BuildRequires : qtdatavis3d
BuildRequires : qtdatavis3d-dev
BuildRequires : qtdeclarative
BuildRequires : qtdeclarative-dev
BuildRequires : qtgamepad
BuildRequires : qtgamepad-dev
BuildRequires : qtgraphicaleffects
BuildRequires : qtimageformats
BuildRequires : qtlocation
BuildRequires : qtlocation-dev
BuildRequires : qtmqtt
BuildRequires : qtmqtt-dev
BuildRequires : qtmultimedia
BuildRequires : qtmultimedia-dev
BuildRequires : qtnetworkauth
BuildRequires : qtnetworkauth-dev
BuildRequires : qtquickcontrols
BuildRequires : qtquickcontrols2
BuildRequires : qtquickcontrols2-dev
BuildRequires : qtremoteobjects-dev
BuildRequires : qtscript
BuildRequires : qtscript-dev
BuildRequires : qtscript-extras
BuildRequires : qtscxml
BuildRequires : qtscxml-dev
BuildRequires : qtsensors
BuildRequires : qtsensors-dev
BuildRequires : qtserialbus
BuildRequires : qtserialbus-dev
BuildRequires : qtserialport
BuildRequires : qtserialport-dev
BuildRequires : qtspeech
BuildRequires : qtspeech-dev
BuildRequires : qtsvg
BuildRequires : qtsvg-dev
BuildRequires : qttools
BuildRequires : qttools-dev
BuildRequires : qttranslations
BuildRequires : qtvirtualkeyboard
BuildRequires : qtvirtualkeyboard-dev
BuildRequires : qtwayland
BuildRequires : qtwayland-dev
BuildRequires : qtwebchannel
BuildRequires : qtwebchannel-dev
BuildRequires : qtwebengine
BuildRequires : qtwebengine-dev
BuildRequires : qtwebsockets
BuildRequires : qtwebsockets-dev
BuildRequires : qtx11extras
BuildRequires : qtx11extras-dev
BuildRequires : qtxmlpatterns
BuildRequires : qtxmlpatterns-dev
BuildRequires : setxkbmap
BuildRequires : shaderc-dev
BuildRequires : shaderc-staticdev
BuildRequires : shared-mime-info
BuildRequires : systemd
BuildRequires : systemd-dev
BuildRequires : texinfo
BuildRequires : tiff-dev
BuildRequires : tiff-staticdev
BuildRequires : uchardet-dev
BuildRequires : uchardet-staticdev
BuildRequires : util-linux
BuildRequires : util-linux-dev
BuildRequires : util-linux-staticdev
BuildRequires : valgrind
BuildRequires : valgrind-dev
BuildRequires : vamp-sdk-dev
BuildRequires : vamp-sdk-staticdev
BuildRequires : wayland
BuildRequires : weston
BuildRequires : wmctrl
BuildRequires : xauth
BuildRequires : xclip
BuildRequires : xdg-dbus-proxy
BuildRequires : xdg-desktop-portal
BuildRequires : xdg-desktop-portal-dev
BuildRequires : xdg-desktop-portal-gtk
BuildRequires : xdg-desktop-portal-kde
BuildRequires : xdg-user-dirs
BuildRequires : xdg-user-dirs-gtk
BuildRequires : xdg-utils
BuildRequires : xdotool
BuildRequires : xdpyinfo
BuildRequires : xf86-input-libinput
BuildRequires : xf86-video-amdgpu
BuildRequires : xf86-video-ati
BuildRequires : xf86-video-fbdev
BuildRequires : xf86-video-nouveau
BuildRequires : xf86-video-qxl
BuildRequires : xf86-video-vboxvideo
BuildRequires : xf86-video-vesa
BuildRequires : xf86-video-vmware
BuildRequires : xfontsel
BuildRequires : xhost
BuildRequires : xinit
BuildRequires : xinput
BuildRequires : xkbcomp
BuildRequires : xkeyboard-config
BuildRequires : xkill
BuildRequires : xmodmap
BuildRequires : xorg-server
BuildRequires : xorg-server-dev
BuildRequires : xorgproto
BuildRequires : xorgproto-dev
BuildRequires : xprop
BuildRequires : xrandr
BuildRequires : xrdb
BuildRequires : xrdp
BuildRequires : xrestop
BuildRequires : xscreensaver
BuildRequires : xsel
BuildRequires : xset
BuildRequires : xsetroot
BuildRequires : xvfb-run
BuildRequires : xwd
BuildRequires : xwininfo
BuildRequires : xz
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : yaml-cpp
BuildRequires : yaml-cpp-dev
BuildRequires : yaml-cpp-staticdev
BuildRequires : zlib
BuildRequires : zlib-dev
BuildRequires : zlib-dev32
BuildRequires : zlib-staticdev
BuildRequires : zstd-dev
BuildRequires : zstd-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: freetype-2.3.0-enable-spr.patch
Patch2: freetype-2.2.1-enable-valid.patch
Patch3: freetype-2.6.5-libtool.patch
Patch4: freetype-2.8-multilib.patch
Patch5: freetype-2.10.0-internal-outline.patch
Patch6: freetype-2.10.1-debughook.patch
Patch7: 0004-Enable-long-PCF-family-names.patch

%description
FreeType 2.10.4
===============
Homepage: https://www.freetype.org
FreeType is a freely available software library to render fonts.

%prep
%setup -q -n freetype
cd %{_builddir}
tar xf %{_sourcedir}/freetype-demos-v2-10-4.tar.gz
cd %{_builddir}/freetype
mkdir -p freetype-demos
cp -r %{_builddir}/freetype-demos/* %{_builddir}/freetype/freetype-demos
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
pushd ..
cp -a freetype build32
popd

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1622264860
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags_pgo content
## pgo generate
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage --coverage -fprofile-partial-training"
export CFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export FCFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export FFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export CXXFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -fvisibility-inlines-hidden -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export LDFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
## pgo use
## -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fPIC -Wl,-z,max-page-size=0x1000 -fvisibility=hidden -flto-partition=none
## gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common -funroll-loops
export PGO_USE="-fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-correction -fprofile-partial-training"
export CFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export FCFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export FFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export CXXFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export LDFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread $PGO_USE"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export PATH="/usr/lib64/ccache/bin:$PATH"
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
## altflags_pgo end
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
ln -sf /builddir/build/BUILD/freetype/ /builddir/build/BUILD/freetype/freetype-demos/subprojects/freetype2
cd freetype-demos/
meson --libdir=lib64 --prefix=/usr --buildtype=release -Ddefault_library=both  -Dzlib=enabled -Dbzip2=enabled -Dpng=enabled -Dharfbuzz=enabled -Dbrotli=enabled -Dmmap=enabled -Ddefault_library=both -Dstrip=false -Dfreetype2:default_library=both -Dfreetype2:zlib=enabled -Dfreetype2:bzip2=enabled -Dfreetype2:png=enabled -Dfreetype2:harfbuzz=enabled -Dfreetype2:brotli=enabled -Dfreetype2:mmap=enabled builddir
## make_prepend content
#sd "\-lz" "/usr/lib64/libz.a" $(fd -uu --glob Makefile)
#sd "\-lbz2" "/usr/lib64/libbz2.a" $(fd -uu --glob Makefile)
#sd "\-lpng" "/usr/lib64/libpng.a" $(fd -uu --glob Makefile)
#sd "\-lpng16" "/usr/lib64/libpng16.a" $(fd -uu --glob Makefile)
#sd "\-lbrotlicommon" "/usr/lib64/libbrotlicommon-static.a" $(fd -uu --glob Makefile)
#sd "\-lbrotlidec" "/usr/lib64/libbrotlidec-static.a" $(fd -uu --glob Makefile)
#sd "\-lbrotlienc" "/usr/lib64/libbrotlienc-static.a" $(fd -uu --glob Makefile)
#
#sd "\-lharfbuzz" "/usr/lib64/libbrotlienc-static.a" $(fd -uu --glob Makefile)
#sd "\-lharfbuzz-subset" "/usr/lib64/libbrotlienc-static.a" $(fd -uu --glob Makefile)
#sd "\-lharfbuzz-icu" "/usr/lib64/libbrotlienc-static.a" $(fd -uu --glob Makefile)
#sd "\-lharfbuzz-gobject" "/usr/lib64/libbrotlienc-static.a" $(fd -uu --glob Makefile)
## make_prepend end
## make_macro start
ninja --verbose %{?_smp_mflags} -v -C builddir
cd /builddir/build/BUILD/freetype
## make_macro end
cd /builddir/build/BUILD/freetype/freetype-demos/builddir
export DISPLAY=:0
export __GL_ALLOW_UNOFFICIAL_PROTOCOL=1
export __GL_SYNC_TO_VBLANK=0
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH=/usr/share/defaults/fonts
export LD_LIBRARY_PATH="/usr/local/cuda/lib64:/usr/local/cuda/targets/x86_64-linux/lib:/usr/nvidia/lib64:/usr/nvidia/lib:/usr/nvidia/lib/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/lib64/dri:/usr/lib64/haswell:/usr/lib64:/usr/lib:/usr/share"
export PATH="/usr/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
export $(dbus-launch)
#
./fttimer "/usr/share/fonts/Inconsolata LGC Nerd Font Complete.ttf" || :
./fttimer "/usr/share/fonts/Inconsolata Bold Nerd Font Complete Mono.ttf" || :
./fttimer "/usr/share/fonts/Inconsolata Bold Nerd Font Complete.ttf" || :
./fttimer "/usr/share/fonts/Inconsolata LGC Bold Italic Nerd Font Complete Mono.ttf" || :
./fttimer "/usr/share/fonts/Inconsolata LGC Bold Italic Nerd Font Complete.ttf" || :
./fttimer "/usr/share/fonts/Inconsolata LGC Bold Nerd Font Complete Mono.ttf" || :
./fttimer "/usr/share/fonts/Inconsolata LGC Bold Nerd Font Complete.ttf" || :
./fttimer "/usr/share/fonts/Inconsolata LGC Italic Nerd Font Complete Mono.ttf" || :
./fttimer "/usr/share/fonts/Inconsolata LGC Italic Nerd Font Complete.ttf" || :
./fttimer "/usr/share/fonts/Inconsolata LGC Nerd Font Complete Mono.ttf" || :
./fttimer "/usr/share/fonts/Inconsolata LGC Nerd Font Complete.ttf" || :
./fttimer "/usr/share/fonts/Inconsolata Regular Nerd Font Complete Mono.ttf" || :
./fttimer "/usr/share/fonts/Inconsolata Regular Nerd Font Complete.ttf" || :
./fttimer "/usr/share/fonts/InconsolataGo Bold Nerd Font Complete Mono.ttf" || :
./fttimer "/usr/share/fonts/InconsolataGo Bold Nerd Font Complete.ttf" || :
./fttimer "/usr/share/fonts/InconsolataGo Nerd Font Complete Mono.ttf" || :
./fttimer "/usr/share/fonts/InconsolataGo Nerd Font Complete.ttf" || :
#
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/Inconsolata LGC Nerd Font Complete.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/Inconsolata Bold Nerd Font Complete Mono.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/Inconsolata Bold Nerd Font Complete.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/Inconsolata LGC Bold Italic Nerd Font Complete Mono.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/Inconsolata LGC Bold Italic Nerd Font Complete.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/Inconsolata LGC Bold Nerd Font Complete Mono.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/Inconsolata LGC Bold Nerd Font Complete.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/Inconsolata LGC Italic Nerd Font Complete Mono.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/Inconsolata LGC Italic Nerd Font Complete.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/Inconsolata LGC Nerd Font Complete Mono.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/Inconsolata LGC Nerd Font Complete.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/Inconsolata Regular Nerd Font Complete Mono.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/Inconsolata Regular Nerd Font Complete.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/InconsolataGo Bold Nerd Font Complete Mono.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/InconsolataGo Bold Nerd Font Complete.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/InconsolataGo Nerd Font Complete Mono.ttf" || :
./ftbench -c 3 -I 40 -l 1 -p "/usr/share/fonts/InconsolataGo Nerd Font Complete.ttf" || :
#
./ftlint 14 "/usr/share/fonts/Inconsolata LGC Nerd Font Complete.ttf" || :
./ftlint 14 "/usr/share/fonts/Inconsolata Bold Nerd Font Complete Mono.ttf" || :
./ftlint 14 "/usr/share/fonts/Inconsolata Bold Nerd Font Complete.ttf" || :
./ftlint 14 "/usr/share/fonts/Inconsolata LGC Bold Italic Nerd Font Complete Mono.ttf" || :
./ftlint 14 "/usr/share/fonts/Inconsolata LGC Bold Italic Nerd Font Complete.ttf" || :
./ftlint 14 "/usr/share/fonts/Inconsolata LGC Bold Nerd Font Complete Mono.ttf" || :
./ftlint 14 "/usr/share/fonts/Inconsolata LGC Bold Nerd Font Complete.ttf" || :
./ftlint 14 "/usr/share/fonts/Inconsolata LGC Italic Nerd Font Complete Mono.ttf" || :
./ftlint 14 "/usr/share/fonts/Inconsolata LGC Italic Nerd Font Complete.ttf" || :
./ftlint 14 "/usr/share/fonts/Inconsolata LGC Nerd Font Complete Mono.ttf" || :
./ftlint 14 "/usr/share/fonts/Inconsolata LGC Nerd Font Complete.ttf" || :
./ftlint 14 "/usr/share/fonts/Inconsolata Regular Nerd Font Complete Mono.ttf" || :
./ftlint 14 "/usr/share/fonts/Inconsolata Regular Nerd Font Complete.ttf" || :
./ftlint 14 "/usr/share/fonts/InconsolataGo Bold Nerd Font Complete Mono.ttf" || :
./ftlint 14 "/usr/share/fonts/InconsolataGo Bold Nerd Font Complete.ttf" || :
./ftlint 14 "/usr/share/fonts/InconsolataGo Nerd Font Complete Mono.ttf" || :
./ftlint 14 "/usr/share/fonts/InconsolataGo Nerd Font Complete.ttf" || :
find . -type f,l -not -name '*.gcno' -not -name 'statuspgo*' -delete -print || :
cd ../../
find builddir/ -type f,l -not -name '*.gcno' -not -name 'statuspgo*' -delete -print || :
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags_pgo content
## pgo generate
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage --coverage -fprofile-partial-training"
export CFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export FCFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export FFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export CXXFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -fvisibility-inlines-hidden -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export LDFLAGS_GENERATE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
## pgo use
## -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fPIC -Wl,-z,max-page-size=0x1000 -fvisibility=hidden -flto-partition=none
## gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common -funroll-loops
export PGO_USE="-fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-correction -fprofile-partial-training"
export CFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export FCFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export FFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export CXXFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export LDFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -Wl,-z,max-page-size=0x1000 -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread $PGO_USE"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export PATH="/usr/lib64/ccache/bin:$PATH"
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
## altflags_pgo end
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
ln -sf /builddir/build/BUILD/freetype/ /builddir/build/BUILD/freetype/freetype-demos/subprojects/freetype2
cd freetype-demos/
meson --libdir=lib64 --prefix=/usr --buildtype=release -Ddefault_library=both  -Dzlib=enabled -Dbzip2=enabled -Dpng=enabled -Dharfbuzz=enabled -Dbrotli=enabled -Dmmap=enabled -Ddefault_library=both -Dstrip=false -Dfreetype2:default_library=both -Dfreetype2:zlib=enabled -Dfreetype2:bzip2=enabled -Dfreetype2:png=enabled -Dfreetype2:harfbuzz=enabled -Dfreetype2:brotli=enabled -Dfreetype2:mmap=enabled builddir
## make_prepend content
#sd "\-lz" "/usr/lib64/libz.a" $(fd -uu --glob Makefile)
#sd "\-lbz2" "/usr/lib64/libbz2.a" $(fd -uu --glob Makefile)
#sd "\-lpng" "/usr/lib64/libpng.a" $(fd -uu --glob Makefile)
#sd "\-lpng16" "/usr/lib64/libpng16.a" $(fd -uu --glob Makefile)
#sd "\-lbrotlicommon" "/usr/lib64/libbrotlicommon-static.a" $(fd -uu --glob Makefile)
#sd "\-lbrotlidec" "/usr/lib64/libbrotlidec-static.a" $(fd -uu --glob Makefile)
#sd "\-lbrotlienc" "/usr/lib64/libbrotlienc-static.a" $(fd -uu --glob Makefile)
#
#sd "\-lharfbuzz" "/usr/lib64/libbrotlienc-static.a" $(fd -uu --glob Makefile)
#sd "\-lharfbuzz-subset" "/usr/lib64/libbrotlienc-static.a" $(fd -uu --glob Makefile)
#sd "\-lharfbuzz-icu" "/usr/lib64/libbrotlienc-static.a" $(fd -uu --glob Makefile)
#sd "\-lharfbuzz-gobject" "/usr/lib64/libbrotlienc-static.a" $(fd -uu --glob Makefile)
## make_prepend end
## make_macro start
ninja --verbose %{?_smp_mflags} -v -C builddir
cd /builddir/build/BUILD/freetype
## make_macro end
pushd ../build32/
export CFLAGS="-O2 -ffat-lto-objects -fuse-linker-plugin -pipe -fPIC -m32 -mstackrealign -march=native -mtune=native"
export CXXFLAGS="-O2 -ffat-lto-objects -fuse-linker-plugin -fvisibility-inlines-hidden -pipe -fPIC -m32 -mstackrealign -march=native -mtune=native"
export LDFLAGS="-O2 -ffat-lto-objects -fuse-linker-plugin -pipe -fPIC -m32 -mstackrealign -march=native -mtune=native"
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
unset LD_LIBRARY_PATH
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
meson --libdir=lib32 --prefix=/usr --buildtype=release -Ddefault_library=both  -Dzlib=enabled \
-Dbzip2=enabled \
-Dpng=enabled \
-Dharfbuzz=disabled \
-Dbrotli=disabled builddir
ninja --verbose %{?_smp_mflags} -v -C builddir
popd

%install
pushd ../build32/
DESTDIR=%{buildroot} ninja -C builddir install
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
## install_macro start
pushd freetype-demos/
DESTDIR=%{buildroot} ninja -C builddir install
popd
## install_macro end
## Remove excluded files
rm -f %{buildroot}/usr/bin/ftbench
rm -f %{buildroot}/usr/bin/ftdiff
rm -f %{buildroot}/usr/bin/ftdump
rm -f %{buildroot}/usr/bin/ftgamma
rm -f %{buildroot}/usr/bin/ftgrid
rm -f %{buildroot}/usr/bin/ftinspect
rm -f %{buildroot}/usr/bin/ftlint
rm -f %{buildroot}/usr/bin/ftmulti
rm -f %{buildroot}/usr/bin/ftsdf
rm -f %{buildroot}/usr/bin/ftstring
rm -f %{buildroot}/usr/bin/ftvalid
rm -f %{buildroot}/usr/bin/ftview
## install_append content
install -dm 0755 %{buildroot}/usr/lib64/haswell/ || :
cp --archive %{buildroot}/usr/lib64/lib*.so* %{buildroot}/usr/lib64/haswell/ || :
## install_append end

%files
%defattr(-,root,root,-)
